import { Filing } from "@/lib/types"

export const filings: Filing[] = [
  {
    id: "fil-001",
    jurisdiction: "Cayman Islands (CIMA)",
    filingType: "Annual Regulatory Return",
    dueDate: "2026-05-31T00:00:00Z",
    status: "in_progress",
    description: "CIMA annual return for registered mutual fund — financial statements and AML compliance attestation required.",
    documents: [
      "Audited financial statements (2025)",
      "AML/CFT compliance officer sign-off",
      "Investor registry (certified copy)",
      "Director declarations",
    ],
  },
  {
    id: "fil-002",
    jurisdiction: "Singapore (MAS)",
    filingType: "MAS Annual Report",
    dueDate: "2026-06-30T00:00:00Z",
    status: "not_started",
    description: "MAS annual report for Registered Fund Management Company — performance, AUM, and compliance disclosures.",
    documents: [
      "AUM certificate",
      "Compliance officer report",
      "Investor complaint log",
      "Risk management framework update",
    ],
  },
  {
    id: "fil-003",
    jurisdiction: "United States (SEC)",
    filingType: "Form D Renewal",
    dueDate: "2026-05-10T00:00:00Z",
    status: "overdue",
    description: "Annual amendment to SEC Form D for Reg D 506(c) exemption. Overdue — filing window closed 3 days ago.",
    documents: [
      "Updated offering details",
      "Total amount sold",
      "Number of investors",
    ],
  },
  {
    id: "fil-004",
    jurisdiction: "ADGM (FSRA)",
    filingType: "Fund Manager License Renewal",
    dueDate: "2026-07-15T00:00:00Z",
    status: "not_started",
    description: "Annual renewal of FSRA Category 3C fund manager license for Gulf Real Estate Income Trust.",
    documents: [
      "Audited accounts",
      "Compliance monitoring report",
      "Controller and UBO declarations",
      "Regulatory business plan update",
    ],
  },
  {
    id: "fil-005",
    jurisdiction: "Cayman Islands (CIMA)",
    filingType: "AML Annual Review",
    dueDate: "2026-04-30T00:00:00Z",
    status: "submitted",
    description: "Annual AML/CFT risk assessment and program review submitted to CIMA-appointed auditor.",
    documents: [
      "AML risk assessment report",
      "KYC policy review",
      "Sanctions screening log",
      "Training records",
    ],
  },
  {
    id: "fil-006",
    jurisdiction: "Hong Kong (SFC)",
    filingType: "Annual Return (Type 9 License)",
    dueDate: "2026-08-31T00:00:00Z",
    status: "not_started",
    description: "SFC annual return for Type 9 (Asset Management) license — required for Pacific Rim Family Office investor access.",
    documents: [
      "Licensed representative declarations",
      "AUM by asset class",
      "Client complaint disclosure",
    ],
  },
  {
    id: "fil-007",
    jurisdiction: "BVI (FSC)",
    filingType: "Private Fund Annual Filing",
    dueDate: "2026-06-01T00:00:00Z",
    status: "in_progress",
    description: "BVI FSC annual filing for private fund registration — Caledonian Trust investor access requires this to remain current.",
    documents: [
      "Fund financial statements",
      "Auditor appointment confirmation",
      "Fund administrator report",
    ],
  },
  {
    id: "fil-008",
    jurisdiction: "Cayman Islands (CIMA)",
    filingType: "Economic Substance Report",
    dueDate: "2026-09-30T00:00:00Z",
    status: "not_started",
    description: "Cayman economic substance reporting for holding company structure — required annually for CIMA compliance.",
    documents: [
      "Core income generating activities report",
      "Local employees and expenditure",
      "Board meeting minutes (Cayman-held)",
    ],
  },
]
